version: '3.8'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user

  dreamsite:
    build: .
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://user:password@db:3306/db?serverVersion=5.7&charset=utf8mb4
      MAILER_DSN: smtp://maildev:2526
    ports:
      - 8020:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: user          # Nom d'utilisateur root pour PhpMyAdmin
      PMA_PASSWORD: password  # Mot de passe root pour PhpMyAdmin
    ports:
      - '8081:80'

  maildev:
    image: djfarrelly/maildev
    ports:
      - '2526:25'   # Port SMTP
      - '1280:1280'   # Port Web
    command: bin/maildev --smtp 2526 --web 1280

# Names our volume
volumes:
  my-db:
